# Generated by Django 5.2.13 on 2026-04-10 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(choices=[('DTF Textil', 'DTF Textil'), ('DTF UV', 'DTF UV'), ('Serigrafía', 'Serigrafía')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En revisión', 'En revisión'), ('En diseño', 'En diseño'), ('Aprobación cliente', 'Aprobación cliente'), ('Producción', 'Producción'), ('Finalizado', 'Finalizado')], default='Nuevo', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
