# Generated by Django 5.2.14 on 2026-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_homecarouselmedia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarouselmedia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
